name: Deploy to GitHub Pages

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vite
        run: npm install -g vite

      - name: Install dependencies
        run: npm install

      - name: Build
        run: tsc && vite build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build_and_push_docker:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ilyagoncharovdev/todoimage:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ilyagoncharovdev/todoimage:latest

  deploy_local:
    runs-on: ubuntu-20.04
    needs: build_and_push_docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull the latest Docker image
        run: docker pull ilyagoncharovdev/todoimage:latest

      - name: Stop and remove the old container
        run: |
          docker stop todoimage-container || true
          docker rm todoimage-container || true

      - name: Run the updated container locally
        run: |
          docker run -d --name todoimage-container -p 5173:5173 ilyagoncharovdev/todoimage:latest
